APDS-61 - add API to list and delete permanent tokens
ArabellaTech/django-rest-framework-jwt pull request #1
Opened 2017-07-21 12:00 UTC by poxip

This also closes APDS-60. 

In this PR I had to drop support for DRF 3.1 and 3.2, because their code is incompatible with Django >= 1.10 (see: https://github.com/encode/django-rest-framework/issues/3252 - it has been fixed in 3.3). I can't do anything about it to make it backwards compatible.

2017-07-21 12:05 UTC, remik requested changes

2017-07-21 12:05 UTC, remik commented on rest_framework_jwt/views.py
> +    def get(self, *args, **kwargs):
Why do we need this and below if you have mixins?

2017-07-21 12:05 UTC, remik commented on tests/test_views.py
> +class DeviceViewTests(TokenTestCase):
Please add devices for not your user to make sure we are not showing it and can't delete.

2017-07-21 12:05 UTC, remik commented on tests/urls.py
> +    url(r'^devices/(?P<pk>[\w]+)$', views.device_delete_view),
Use router.

2017-07-21 13:06 UTC, poxip commented on rest_framework_jwt/views.py
> +    def get(self, *args, **kwargs):
Mixins used here, only add the "destroy" and "list" methods

2017-07-21 13:12 UTC, remik commented on rest_framework_jwt/views.py
> +    def get(self, *args, **kwargs):
We used mixins so router should discover it. Check: http://www.django-rest-framework.org/api-guide/viewsets/

2017-07-21 18:02 UTC, poxip commented
The tests are okay (see details), Travis does not provide Python3.3 somehow (it works in the original repo though). We do not have to drop support for DRF 3.0, 3.1, 3.2 because those versions are only supposed to work with Django 1.8 and 1.9.

2017-07-24 10:52 UTC, poxip commented on tests/test_views.py
> +class DeviceViewTests(TokenTestCase):
Added in the CR commit.

2017-07-25 12:21 UTC, jacoor requested changes

2017-07-25 12:21 UTC, jacoor commented on rest_framework_jwt/models.py
> +    last_request_datetime = models.DateTimeField(auto_now=True)
Missing empty line at the end of file.
Pylint and pep8 will complain.

2017-07-25 12:21 UTC, jacoor commented on rest_framework_jwt/serializers.py
> +        fields = ['permanent_token', 'jwt_secret', 'created', 'name', 'details', 'last_request_datetime']
WHat?! you return JWT secret to the world? 
http://getblimp.github.io/django-rest-framework-jwt/#jwt_secret_key Please check documentation what JWT secret is.

2017-07-25 12:21 UTC, jacoor commented on tests/test_views.py
> +            'permanent_token', 'jwt_secret', 'created', 'name', 'details', 'last_request_datetime'
Please, do not make any field *_secret_* public. After all, there is a reason why they call it secret.
http://getblimp.github.io/django-rest-framework-jwt/#jwt_secret_key

2017-07-25 13:34 UTC, poxip commented on rest_framework_jwt/models.py
> +    last_request_datetime = models.DateTimeField(auto_now=True)
GitHub does not show the last empty line as far as I remember. The flake8 task in tox did not complain, see: https://travis-ci.org/ArabellaTech/django-rest-framework-jwt/jobs/256993179

2017-08-01 11:15 UTC, remik approved these changes

2017-08-01 12:21 UTC, merged