APDS-63 - [BE] disallow passing permanent_token header i
ArabellaTech/django-rest-framework-jwt pull request #4
Opened 2017-07-23 20:37 UTC by poxip

Disallow passing permanent_token header in views other than the Device's token refresh view.

This requires APDS-62 (create view to refresh device's token) to be completed. I will add reviewers after it's done.

2017-07-25 11:43 UTC, jacoor requested changes

2017-07-25 11:43 UTC, jacoor commented on rest_framework_jwt/serializers.py
> +            'permanent_token': permanent_token,
And why do you return permanent token here?

2017-07-25 11:43 UTC, jacoor commented on rest_framework_jwt/views.py
>          return Response({}, status=status.HTTP_200_OK)
you can send device id in response to login for them to store which should be send everytime in headers.
Or they can send you permanent token in delete call.

2017-07-25 11:43 UTC, jacoor commented on rest_framework_jwt/views.py
>          return Response({}, status=status.HTTP_200_OK)
PLeasae also do not leave it as "200 OK" - just raise exception always until it is implemented.

2017-07-25 11:43 UTC, jacoor commented on rest_framework_jwt/views.py
> +class DeviceViewSet(HeadersCheckMixin, mixins.ListModelMixin, mixins.DestroyModelMixin, viewsets.GenericViewSet):
why viewset instead of just API*

2017-07-27 09:50 UTC, jacoor requested changes

2017-07-27 09:50 UTC, jacoor commented on rest_framework_jwt/serializers.py
> +            'user': device.user
why you return user?
User is already(should be) encoded in JWT token, isn't it?

2017-07-27 09:56 UTC, jacoor commented on rest_framework_jwt/serializers.py
> +            'user': device.user
Even if not, it should not return user, only token. And, btw, why you return manually data instead of using serializers?

2017-07-27 10:25 UTC, poxip commented on rest_framework_jwt/serializers.py
> +            'user': device.user
I based this on the JSONWebTokenSerializer above.

2017-07-27 10:30 UTC, jacoor commented on rest_framework_jwt/serializers.py
> +            'user': device.user
Understood. Our implementation encodes user in JWT token, as you remember. Keep as is for now please.  We will update later
@remik  FYI.

2017-08-01 11:46 UTC, merged