APDS-64 - [BE] add API to logout device
ArabellaTech/django-rest-framework-jwt pull request #6
Opened 2017-07-24 11:28 UTC by poxip

2017-07-25 11:59 UTC, jacoor requested changes

2017-07-25 11:59 UTC, jacoor commented on rest_framework_jwt/views.py
> +    def get(self, request):
Not get but delete. It is after all delete call.

2017-07-25 11:59 UTC, jacoor commented on rest_framework_jwt/views.py
> +        return Response({}, status=status.HTTP_200_OK)
Delete returns 204 No response.

2017-07-25 11:59 UTC, jacoor commented on rest_framework_jwt/views.py
> +            Device.objects.get(
Use some ID that FE will send to find device. Name is not unique.

2017-07-27 09:28 UTC, jacoor requested changes

2017-07-27 09:28 UTC, jacoor commented on rest_framework_jwt/views.py
> +    def get_object(self):
Why two? You have get_queryset and get object. I'd use only get object, there is no point in keeping two functions.

2017-07-27 10:26 UTC, poxip commented on rest_framework_jwt/views.py
> +    def get_object(self):
But the get_object() uses the get_queryset(), but yeah, it can be done in the get_object()

2017-07-27 13:11 UTC, poxip commented on rest_framework_jwt/views.py
> +    def get_object(self):
Covered in the latest CR commit.

2017-08-01 11:48 UTC, merged